events {
}
http {
    include /etc/nginx/mime.types;
    upstream django_server {
        server django:8080;
    }
    
    #include /etc/nginx/mime.types;
    #sendfile on;

    server {
        listen 80;
        server_name dash-faromoro.blueocean.com.py www.dash-faromoro.blueocean.com.py;

         add_header Content-Security-Policy "script-src 'self' 'unsafe-inline' https://kit.fontawesome.com https://code.jquery.com https://cdnjs.cloudflare.com https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://kit.fontawesome.com https://fonts.googleapis.com https://cdnjs.cloudflare.com https://cdn.jsdelivr.net;" always;


        location / {
            proxy_pass http://django_server;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_redirect off;
            
        }

        location /static/ {
            alias /app/static/;
        }

        location /licenseimage/ {
            alias /app/licenseimage/;
            autoindex on;
        }

        location /detectionimage/ {
            alias /app/detectionimage/;
            autoindex on;
        }
    }
}
